version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./public:/usr/share/nginx/html:cached
  websocket:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 6001:6001
    command: sh -c "php artisan websockets:serve"
    volumes:
      - .:/var/www:cached
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www:cached
