version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${HTTP_PORT:-8080}:80
    volumes:
      - ./public:/usr/share/nginx/html:cached
  websocket:
    build:
      context: .
      dockerfile: docker/websockets/Dockerfile
    ports:
      - 6001:6001
    volumes:
      - .:/var/www:cached
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www:cached
  cron:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    entrypoint: ["docker-cron-entrypoint"]
    volumes:
      - .:/var/www:cached
